import {
	ActionDirector,
	AnimalHandler,
	ArtAssistant,
	ArtDirector,
	AssistantChoreographer,
	AssistantDirector,
	AssistantEditor,
	CastingAssistant,
	CastingDirector,
	Choreographer,
	Colourist,
	CostumeAssistant,
	CostumeStylist,
	DA,
	DIT,
	DOP,
	DOPProductShoot,
	Director,
	Dressman,
	DronePilot,
	ExecutiveProducer,
	FirstAC,
	FirstAD,
	FocusPuller,
	FoodStylist,
	Gaffer,
	HMUAssistant,
	HairMakeup,
	HairStylist,
	HairStylistAssistant,
	HandModels,
	KeyGrips,
	LineProducer,
	LiveSoundRecordist,
	LocationManager,
	Lyrics,
	MakeupArtist,
	MakeupArtistAssistant,
	MusicDirector,
	Musician,
	OfflineEditor,
	OnlineAssistant,
	OnlineEditor,
	PackMaker,
	PhotographerAssistant,
	Photographer,
	PhotographyRetouching,
	PostProducer,
	Producer,
	ProductionAssistant,
	ProductionController,
	ProductionDesigner,
	ProductionDesignerAssistant,
	ProductionManager,
	ProstheticMakeup,
	SetDecorator,
	Singer,
	SoundEngineer,
	SteadicamOperator,
	StoryboardArtist,
	Unit2DOP,
	Unit2Director,
	VFX,
	VoiceOver,
	BGArtistCoordinator,
	VFXGenre,
	DigitalAd,
	Documentary,
	Feature,
	Infomercial,
	MusicVideo,
	Reels,
	Series,
	Short,
	TvcDigitalAd,
	Action,
	Adventure,
	Celebrity,
	Children,
	Emotional,
	Fantasy,
	Humour,
	Montage,
	Musical,
	Others,
	Historic,
	Product,
	PublicAnnouncements,
	Reality,
	Dialogue,
	Romance,
	Rural,
	ScienceFiction,
	SliceOfLife,
	Sports,
	Testimonial,
	UserGeneratedContent,
	PackShootSFX,
	Agency,
	Brand,
	StudioUser,
	UnderwaterDoP,
} from '@touchblack/icons';

const iconmap = (color: string, size?: string) => ({
	'2nd unit director': () => <Unit2Director color={color} size={size} />,
	'2nd unit directora': () => <Unit2Director color={color} size={size} />,
	'2nd unit dop': () => <Unit2DOP color={color} size={size} />,
	'action director': () => <ActionDirector color={color} size={size} />,
	'animal handler': () => <AnimalHandler color={color} size={size} />,
	'art assistant': () => <ArtAssistant color="none" stroke={color} size={size} />,
	'art director': () => <ArtDirector color="none" stroke={color} size={size} />,
	'assistant choreographer': () => <AssistantChoreographer color="none" stroke={color} size={size} />,
	'assistant director': () => <AssistantDirector color={color} size={size} />,
	'assistant editor': () => <AssistantEditor color={color} size={size} />,
	'background artist': () => <BGArtistCoordinator color="none" stroke={color} size={size} />,
	'casting assistant': () => <CastingAssistant color={color} size={size} />,
	'casting director': () => <CastingDirector color={color} size={size} />,
	choreographer: () => <Choreographer color="none" stroke={color} size={size} />,
	colourist: () => <Colourist color="none" stroke={color} size={size} />,
	'costume assistant': () => <CostumeAssistant color={color} size={size} />,
	'costume stylist': () => <CostumeStylist color={color} size={size} />,
	da: () => <DA color="none" stroke={color} size={size} />,
	director: () => <Director color={color} size={size} />,
	dit: () => <DIT color={color} size={size} />,
	dop: () => <DOP color={color} size={size} />,
	'dop product shoot': () => <DOPProductShoot color={color} size={size} />,
	dressman: () => <Dressman color={color} size={size} />,
	'drone pilot': () => <DronePilot color="none" stroke={color} size={size} />,
	'executive producer': () => <ExecutiveProducer color={color} size={size} />,
	'first ac': () => <FirstAC color={color} size={size} />,
	'first ad': () => <FirstAD color={color} size={size} />,
	'focus puller': () => <FocusPuller color={color} size={size} />,
	'food stylist': () => <FoodStylist color="none" stroke={color} size={size} />,
	gaffer: () => <Gaffer color={color} size={size} />,
	grips: () => <KeyGrips color="none" stroke={color} size={size} />,
	'hair and makeup': () => <HairMakeup color="none" stroke={color} size={size} />,
	'hair stylist': () => <HairStylist color="none" stroke={color} size={size} />,
	'hair stylist assistant': () => <HairStylistAssistant color={color} size={size} />,
	'hand models': () => <HandModels color="none" strokeColor={color} size={size} />,
	'hmu assistant': () => <HMUAssistant color="none" stroke={color} size={size} />,
	'line producer': () => <LineProducer color={color} size={size} />,
	'live sound recordist': () => <LiveSoundRecordist color={color} size={size} />,
	'location manager': () => <LocationManager color={color} size={size} />,
	lyrics: () => <Lyrics color={color} size={size} />,
	'makeup artist': () => <MakeupArtist color="none" stroke={color} size={size} />,
	'makeup artist assistant': () => <MakeupArtistAssistant color={color} size={size} />,
	'music director': () => <MusicDirector color={color} size={size} />,
	musician: () => <Musician color="none" stroke={color} size={size} />,
	'offline editor': () => <OfflineEditor color={color} size={size} />,
	'online assistant': () => <OnlineAssistant color={color} size={size} />,
	'online editor': () => <OnlineEditor color={color} stroke="none" size={size} />,
	'pack maker': () => <PackMaker color={color} size={size} />,
	photographer: () => <Photographer color={color} size={size} />,
	'photographer assistant': () => <PhotographerAssistant color="none" stroke={color} size={size} />,
	'post producer': () => <PostProducer color="none" stroke={color} size={size} />,
	producer: () => <Producer color={color} size={size} />,
	'production assistant': () => <ProductionAssistant color={color} size={size} />,
	'production controller': () => <ProductionController color={color} size={size} />,
	'production designer': () => <ProductionDesigner color="none" stroke={color} size={size} />,
	'production designer assistant': () => <ProductionDesignerAssistant color="none" stroke={color} size={size} />,
	'production manager': (props: any) => <ProductionManager color={color} size={size} {...props} />,
	'product stylist': () => <ProductionDesigner color="none" stroke={color} size={size} />,
	'prosthetics and sfx makeup': () => <ProstheticMakeup color={color} size={size} />,
	'prosthetics / sfx makeup': () => <ProstheticMakeup color={color} size={size} />,
	'prosthetics makeup': () => <ProstheticMakeup color={color} size={size} />,
	retouching: () => <PhotographyRetouching color={color} size={size} />,
	'set decorator': () => <SetDecorator color={color} size={size} />,
	singer: () => <Singer color={color} size={size} />,
	'sound engineer': () => <SoundEngineer color={color} size={size} />,
	'steadicam operator': () => <SteadicamOperator color={color} size={size} />,
	'storyboard artist': () => <StoryboardArtist color="none" stroke={color} size={size} />,
	vfx: () => <VFX color="none" stroke={color} size={size} />,
	'voice over': () => <VoiceOver color={color} size={size} />,
	'animation/cg/vfx': () => <VFXGenre color={color} size={size} />,
	'digital ad': () => <DigitalAd color={color} size={size} />,
	documentary: () => <Documentary color={color} size={size} />,
	feature: () => <Feature color={color} size={size} />,
	'infomercial/corporate': () => <Infomercial color="none" stroke={color} size={size} />,
	'music video': () => <MusicVideo color={color} size={size} />,
	reels: () => <Reels color={color} size={size} />,
	series: () => <Series color={color} size={size} />,
	short: () => <Short color={color} size={size} />,
	'tvc and digital ad': () => <TvcDigitalAd color="none" stroke={color} size={size} />,
	action: (props: any) => <Action color="none" stroke={color} size={size} {...props} />,
	'dfe5010b-790f-431f-8553-1f914e35cc2a': (props: any) => <Action color={color} size={size} {...props} />,
	adventure: (props: any) => <Adventure color={color} size={size} {...props} />,
	'2fa4e5bd-19c1-4aaa-acb9-e458ddd728b5': (props: any) => <Adventure color={color} size={size} {...props} />,
	celebrity: (props: any) => <Celebrity color="none" stroke={color} size={size} {...props} />,
	'247d6f10-163f-41c3-bc8c-79bcef1b99a2': (props: any) => <Celebrity color="none" stroke={color} size={size} {...props} />,
	children: (props: any) => <Children color={color} size={size} {...props} />,
	'51427de6-7238-4d01-a3cd-a764e9dfacc9': (props: any) => <Children color={color} size={size} {...props} />,
	emotional: (props: any) => <Emotional color={color} size={size} {...props} />,
	'c111b700-eac0-40d9-8065-09ab1ef6be80': (props: any) => <Emotional color={color} size={size} {...props} />,
	fantasy: (props: any) => <Fantasy color={color} size={size} {...props} />,
	'fa8f55d2-3d2d-4fe7-9e99-72931dcb393a': (props: any) => <Fantasy color={color} size={size} {...props} />,
	'genre test': (props: any) => <VFXGenre color={color} size={size} {...props} />,
	'dcf8cc22-c2ae-4931-955d-4c9cbcd4c1d9': (props: any) => <VFXGenre color={color} size={size} {...props} />,
	humour: (props: any) => <Humour color={color} size={size} {...props} />,
	'4a695eb3-1a09-4999-b89a-7b80a369fd48': (props: any) => <Humour color={color} size={size} {...props} />,
	montage: (props: any) => <Montage color={color} size={size} {...props} />,
	'dd7995f3-da31-4a28-af08-116b399ef4a6': (props: any) => <Montage color={color} size={size} {...props} />,
	musical: (props: any) => <Musical color={color} size={size} {...props} />,
	'fa800ff0-82cb-4a16-9f38-5ae6da46c4dd': (props: any) => <Musical color={color} size={size} {...props} />,
	others: (props: any) => <Others color={color} size={size} {...props} />,
	'6994e020-7659-4a43-a9bc-d0dac1af22d0': (props: any) => <Others color={color} size={size} {...props} />,
	'period and historic': (props: any) => <Historic color={color} size={size} {...props} />,
	'7a48d8b6-e040-4da2-8030-6e19d9a8ee8a': (props: any) => <Historic color={color} size={size} {...props} />,
	'period historic': (props: any) => <Historic color={color} size={size} {...props} />,
	'f4c1738c-fae8-4b40-8224-ed6404d8ade1': (props: any) => <Historic color={color} size={size} {...props} />,
	product: (props: any) => <Product color={color} size={size} {...props} />,
	'ef455b50-3e1c-4fa4-8e58-2be86144a776': (props: any) => <Product color={color} size={size} {...props} />,
	'public service announcements': (props: any) => <PublicAnnouncements color={color} size={size} {...props} />,
	'07c55e06-07fd-49b0-9ce8-f439e5d99ac5': (props: any) => <PublicAnnouncements color={color} size={size} {...props} />,
	reality: (props: any) => <Reality color={color} size={size} {...props} />,
	'7d829853-9677-48f7-a60d-6b38d81e9270': (props: any) => <Reality color={color} size={size} {...props} />,
	'repartee and dialogue': (props: any) => <Dialogue color={color} size={size} {...props} />,
	'399864fb-2bdd-491b-8e25-a8b281054117': (props: any) => <Dialogue color={color} size={size} {...props} />,
	'repartee dialogue': (props: any) => <Dialogue color={color} size={size} {...props} />,
	'684e02ab-6db6-487b-b63b-863f92533a55': (props: any) => <Dialogue color={color} size={size} {...props} />,
	romance: (props: any) => <Romance color={color} size={size} {...props} />,
	'084b57f0-baaf-470f-9b7b-b80fdda2bb10': (props: any) => <Romance color={color} size={size} {...props} />,
	rural: (props: any) => <Rural color={color} size={size} {...props} />,
	'a4f7efa7-4431-4148-b409-3ce749fc9108': (props: any) => <Rural color={color} size={size} {...props} />,
	'science fiction': (props: any) => <ScienceFiction color={color} size={size} {...props} />,
	'8a53a4dd-1d2f-489a-8d8e-f755348df84b': (props: any) => <ScienceFiction color={color} size={size} {...props} />,
	'slice of life': (props: any) => <SliceOfLife color={color} size={size} {...props} />,
	'74f10194-419e-4e81-857f-875f917b2157': (props: any) => <SliceOfLife color={color} size={size} {...props} />,
	sports: (props: any) => <Sports color={color} size={size} {...props} />,
	'49d11dc7-2b6b-4b8f-bc78-cd1d252c9431': (props: any) => <Sports color={color} size={size} {...props} />,
	testimonial: (props: any) => <Testimonial color={color} size={size} {...props} />,
	'990d067c-a3f5-4c49-932b-321d3bf898a4': (props: any) => <Testimonial color={color} size={size} {...props} />,
	'user generated content': (props: any) => <UserGeneratedContent color={color} size={size} {...props} />,
	'd4d6101f-6522-4e6b-9b5e-7c87656d1ade': (props: any) => <UserGeneratedContent color={color} size={size} {...props} />,

	/* ids */
	'0147bb5c-318e-41ab-a053-be14bb4bd7c8': () => <VFXGenre color={color} size={size} />,
	'c1e21443-3796-4100-993b-9f5ac73d5765': () => <DigitalAd color={color} size={size} />,
	'c190cb1f-bc1f-4c62-9f21-81481e31b8aa': () => <Documentary color={color} size={size} />,
	'd3f856da-c9a8-457e-a307-46ea04759ead': () => <Feature color={color} size={size} />,
	'0bb357ac-f3a4-46a1-8acf-41fc9cef37a6': () => <Infomercial color={color} size={size} />,
	'4de44c8c-12df-4860-9bcd-7b25c9f9343a': () => <MusicVideo color={color} size={size} />,
	'bfc7e0bd-4b70-41ac-8426-be88815df051': () => <Reels color={color} size={size} />,
	'aa0cb87d-2bcf-4ecd-bed5-9ba93ee5f083': () => <Series color={color} size={size} />,
	'f4d19151-3160-4be1-8445-d1217c7aa9ca': () => <Short color={color} size={size} />,
	'8615842f-ed2e-402a-8630-e226baa995db': () => <TvcDigitalAd color={color} size={size} />,

	'background artist coordinator': (props: any) => <BGArtistCoordinator color={color} size={size} />,
	agency: (props: any) => <Agency color={color} size={size} />,
	brand: (props: any) => <Brand color={color} size={size} />,
	'studio user': (props: any) => <StudioUser color={color} size={size} />,
	'underwater dop': (props: any) => <UnderwaterDoP color={color} size={size} />,
	'pack shoot and sfx': (props: any) => <PackShootSFX color={color} size={size} />,
});
export default iconmap;
