import CONSTANTS from '../constants/constants';
import { Platform, SafeAreaView, ScrollView, StyleSheet } from 'react-native';
import Header from '@components/Header';
import RenderHtml, { defaultSystemFonts } from 'react-native-render-html';
import { useStyles } from 'react-native-unistyles';

export default function PrivacyPolicy() {
	const { styles, theme } = useStyles(stylesheet);
	const source = `
<div style="color: whitesmoke; font-size: 16px; padding: 0 16px; font-family: CabinetGrotesk-Regular;">
	<p style="font-weight: bold">Last updated: 17th May 2024</p>
	<div style="font-weight: bold;">
		We are committed to keep your personal data secure and being transparent about our practices. We adhere to the
		standard industry practices to secure information collected from You.
	</div>
	<br />
	<div>
		<span style="font-weight: bold;">Talent Grid Pvt Ltd</span>, having its registered office at Flat 001, Fort St
		Johns Apartment, 21 Rukmini Colony,
		Sivanchetti Gardens, Bengaluru, India 560042 (“<span style="font-weight: bold;">Company</span>” or “<span
			style="font-weight: bold;">we</span>” or “<span style="font-weight: bold;">us</span>”), is the owner of the
		website domain at
		<span style="font-weight: bold;">https://talentgridnow.com</span> and mobile application titled “<span
			style="font-weight: bold;">Talent Grid</span>” available on the Google Play Store/Apple App
		Store, respectively (collectively referred as “<span style="font-weight: bold;">Platform</span>”) and any
		service availed by Users (hereinafter referred
		to as “<span style="font-weight: bold;">you</span>”, “<span style="font-weight: bold;">your</span>” or “<span
			style="font-weight: bold;">User</span>”) through the Platform is governed by the Terms of Service as
		available on Platform
		and this privacy policy (“<span style="font-weight: bold;">Privacy Policy</span>”). This Privacy Policy
		(i) shall apply to any person who visits,
		browses, uses or accesses the Platform or use any Services on the Platform;
		(ii) provides you with information
		on the purposes and manner of handling your personal data by us
		<br />
		<br />
		This Privacy Policy has been drafted and is published in compliance with the Information Technology Act, 2000,
		and applicable amendments, rules, regulations and guidelines enacted thereunder from time to time (“<span
			style="font-weight: bold;">IT Act</span>”)
		with specific mention of regulation 4 of the Information Technology (Reasonable Security Practices and
		Procedures and Sensitive personal information) Rules, 2011 (“<span style="font-weight: bold;">SPDI
			Rules</span>”) and the Information Technology
		(Intermediary Guidelines and Digital Media Ethics Code) Rules, 2023, and any other national and state laws which
		relate the processing of data. This Privacy Policy is an electronic record in terms of the IT Act and this
		electronic record is generated by a computer system and does not require any physical or digital signatures. Any
		new features and/or services that are added to our current Services at any point in the future shall also be
		subject to the terms set out in this Privacy Policy along with any other future relevant legislations to be
		incorporated as per the laws of the land.
	</div>
	<br />
	<div>
		We use your data to provide and improve the Platform. By using the Platform, you agree to the collection and use
		of information in accordance with this Privacy Policy
	</div>
	<br />
	<div>
		<span style="font-weight: bold;">1. INTRODUCTION AND APPLICABILITY OF THE PRIVACY POLICY</span>
		<ol type="I">
			<li>
				We are strongly committed to respecting your online privacy and recognize the need for appropriate
				protection and management of any personal information collected and/or collated by us.
			</li>
			<li>
				The purpose of this Privacy Policy is to ensure that there is an intact charter that governs the
				collection, usage and protection of any personal and/or sensitive data collected by us. This Policy
				informs
				our
				Users/ visitors of our procedures regarding collection, usage, storage, processing, disclosure, sharing
				and
				protection of any Personal Data or Sensitive Personal Data obtained by us through the Platform.
			</li>
			<li>
				Any reference made to Privacy Policy in this document shall mean and refer to the latest version of
				the
				Privacy Policy
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">2. DISCLAIMER</span>
		<ol type="I">
			<li>
				Please be advised that any Information (as defined herein below) procured by us, shall be:
				<ul>
					<li>
						processed fairly and lawfully for rendering the Services (as defined in the Terms of Service);
					</li>
					<li>
						obtained only for specified and lawful purposes, and not be used in any manner which is against
						the
						law
						or policy in force in India (“Applicable Law”);
					</li>
					<li>
						adequate, relevant, and not excessive in relation to the purpose for which it is required;
					</li>
					<li>
						able to be reviewed by the User, from time to time and updated-if need arises; and
					</li>
					<li>
						not kept longer than for the time which it is required or the purpose for which it is required
						or as
						required by the applicable law.
					</li>
				</ul>
			</li>
			<br />
			<li>
				WE SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE SUSTAINED BY REASON OF ANY DISCLOSURE (INADVERTENT OR
				OTHERWISE) OF ANY OF YOUR INFORMATION AND DATA, IF THE SAME IS EITHER (A) REQUIRED FOR SHARING YOUR
				INFORMATION
				FOR LEGITIMATE PURPOSES; OR (B) WAS EFFECTED THROUGH NO FAULT, ACT, OR OMISSION OF THE COMPANY OR (C)
				WAS
				EFFECTED IN OFFERING OF OUR LAWFUL SERVICES OR (D) IS ATTRIBUTABLE TO THE NEGLIGENCE OF THE USER.
			</li>
			<br />
			<li>
				BY USING THE PLATFORM OR SERVICES, YOU EXPLICITLY ACCEPT, WITHOUT LIMITATION OR QUALIFICATION, THE
				COLLECTION, USE AND TRANSFER OF THE INFORMATION/ DATA IN THE MANNER DESCRIBED HEREIN.
			</li>
			<br />
			<li>
				PLEASE READ THIS PRIVACY POLICY CAREFULLY AS IT AFFECTS YOUR RIGHTS AND LIABILITIES UNDER LAW.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">3. YOUR CONSENT:</span>
		<ol type="I">
			<li>
				Please note that by providing the Information (as defined herein below), you provide your consent and
				authorize us to collect, use or disclose such Information for the business and research purposes and as
				stated
				in this Policy, and as permitted or required by applicable law. Moreover, you understand and hereby
				consent that
				this Information may be transferred to any third party for the purpose of providing Services through the
				Platform or to any third-party providers.
			</li>
			<li>
				This Privacy Policy shall be enforceable against you in the same manner as any other written agreement.
				By
				visiting or accessing the Platform and voluntarily providing us with Information (including Personal
				Data), you
				are consenting to our use of the Information, in accordance with this Privacy Policy. If you do not
				agree with
				this Privacy Policy, you may choose to not provide us with any Personal Data and/or Sensitive Personal
				Data.
				Under such circumstance, we may be unable to render Services.
			</li>
			<li>
				Such an intimation to withdraw your consent can be sent to <span
					style="font-weight: bold;">Support@talentgridnow.com</span>.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">4. TYPES OF DATA COLLECTED</span>
		<ol type="I">
			<li>
				We collect the following information for the purposes mentioned in this Privacy Policy.
				<ul>
					<li>
						Personal data including names, addresses, phone numbers, bank accout details, permanent
						account
						number
						and any other publicly available personal data;
					</li>
					<li>
						“Transaction Information” means information that is contained in text messages (that is,
						SMS)
						sent by
						providers of services and/or products (including but not limited to financial institutions,
						mobile
						carriers and
						utility companies) to your mobile telephone number(s) in connection with one or more
						transactions
						across
						multiple financial accounts (including purchase, payments, billing information and service
						notifications
						related
						thereto). Without limitation, Transaction Information includes:
						mobile phone number, email address, partial payment card data only to the extent such card data
						is
						disclosed in
						the said messages, information related to the transaction in question including identity of the
						service
						and the
						price or fee paid or payable in respect thereof, KYC details
					</li>
					<li>
						“Technical Information”: any information gathered through various technologies that may
						employ
						cookies,
						web beacons, or similar technologies to automatically record certain information from your
						device
						through which
						you use the Platform. This technical information may include your Internet Protocol (IP)
						address,
						device
						or
						browser type, Internet service provider (ISP), referring or exit pages, clickstream data,
						operating
						system,
						hardware model, operating system version, unique device identifiers, and mobile network. This
						data
						includes
						usage information and user statistics;
					</li>
					<li>
						“Locational Information”: the information obtained through GPS or other means, such as
						the
						geographical
						location of the User;
					</li>
					<li>
						“Information for use of our service” means information which is shared with us to avail
						our
						Services; and
					</li>
					<li>
						“Non-personal information” means any information that does not reveal your specific
						identity,
						such as,
						browser information, information collected through Cookies (as defined below), pixel tags and
						other
						technologies, demographic information. LifeX gathers some information automatically when you
						visit
						the
						Platform.
						When you use the Platform, we may collect certain information about your computer or mobile to
						facilitate,
						evaluate and verify your use of the Platform. For example, we may store environmental variables,
						such as
						browser
						type, operating system, speed of the central processing unit (CPU), referring or exit web pages,
						click
						patterns
						and the internet protocol (IP) address of your computer. This information is generally collected
						in
						aggregate
						form, without identifying any user individually.
					</li>
				</ul>
			</li>
			(All the types of data mentioned above shall be collectively referred to as “<span
				style="font-weight: bold;">Information</span>”)
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">5. PURPOSE OF COLLECTION AND USAGE OF DATA</span>
		<ol type="I">
			<li>
				The Information collected by us shall be used for availing our Platform and utilised for other
				functions
				including but not limited to:
				<ul>
					<li>
						offering services and technical support to the users;
					</li>
					<li>
						processing payments made by the users and maintaining related financial records such as
						invoices;
					</li>
					<li>
						employment purposes;
					</li>
					<li>
						analysing the usage to better serve your purpose;
					</li>
					<li>
						sending you requested information about the service;
					</li>
					<li>
						responding to service requests, questions, and concerns;
					</li>
					<li>
						administering your account;
					</li>
					<li>
						sending you promotional and marketing communications (where you have requested us to do so);
					</li>
					<li>
						facilitating your transactions with other users when you use our service;
					</li>
					<li>
						protecting our services (for example, fraud monitoring and prevention);
					</li>
					<li>
						enforcing our agreements or policies;
					</li>
					<li>
						requesting feedback; and
					</li>
					<li>
						complying with any legal obligation.
					</li>
				</ul>
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">6. DISCLOSURE AND SHARING OF INFORMATION</span>
		<ol type="I">
			<li>
				We do not rent, sell or disclose or share any information that we collect from you, with third
				parties,
				save and except in order to provide you with the Services. Any such disclosure, if made, shall be in
				accordance
				to this Privacy Policy and as per the procedure prescribed by law and in compliance with our legal
				obligations.
				We may share your Information in circumstances and for the purposes as specified hereunder:
				<ul>
					We shall share the information to the third-party service providers/ vendors, to provide you
					with
					the
					Services. This may include but not be limited to, storage providers, data analytics providers,
					consultants,
					lawyers, and auditors.
					<li>
						When compelled by law, we may disclose any Information provided by you on the Platform as
						may
						be
						deemed
						to be necessary or appropriate:
						<ul>
							<li>
								under applicable law, including laws outside your country of residence;
							</li>
							<li>
								to comply with legal process;
							</li>
							<li>
								to respond to requests from public, regulatory, legal enforcement and government
								authorities
								including
								public and government authorities outside your country of residence;
							</li>
							<li>
								to allow us to comply with any judgement or decree or order issued under any law for
								the
								time
								being
								in
								force
								in India, or any judgment or order relating to claims of a contractual or civil nature
								under
								any
								law
								for
								the
								time being in force outside India;
							</li>
							<li>
								to protect our operations or those of any of our affiliates;
							</li>
							<li>
								to protect our rights, privacy, safety or property, and/that of our affiliates, you
								or
								others;
							</li>
							<li>
								to allow us to pursue available remedies or limit the damages that we may sustain;
								or
							</li>
							<li>
								to protect against legal liability or loss, such as prevention of corporate
								espionage,
								maintenance
								of
								confidentiality of trade secrets, intellectual property, classified information;
							</li>
							<li>
								to protect the personal safety of Users of the Platform;
							</li>
							<li>
								to prevent or investigate possible wrongdoing in connection with the Platform.
							</li>
						</ul>
					</li>
					<li>
						Employees /Agents of Company: We follow a strict confidentiality policy with regard to
						disclosure
						of
						confidential information to our employees or other personnel. We may disclose the Information
						only
						to
						those
						of
						our employees and other personnel on a need to know basis. Any breach of confidential
						information by
						the
						employees, personnel within the Company is dealt with stringently by us.
					</li>
				</ul>
			</li>

			<li>
				We may remove parts of data that can identify you and share anonymized data with other parties. We
				may
				also
				combine your information with other information in a way that it is no longer associated with you and
				share
				that
				aggregated information.
			</li>
			<li>
				For the Information disclosed pursuant to sub-clause (a), (d) and (e) of Clause 6.1 above, Company
				may
				share Information only if you authorize us to do so.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">7. TRANSFER OF DATA</span>
		<ol type="I">
			<li>
				Your Information may be transferred to, and maintained on, computers located in India
			</li>
			<li>
				If you are located outside India and choose to provide information to us, please note that we may
				transfer
				the data to India to process the Information.
			</li>
			<li>
				Your consent to this Privacy Policy followed by your submission of such information represents your
				unconditional agreement to that transfer or use.
			</li>
			<li>
				We will take all steps reasonably necessary to ensure that your data is treated securely and in
				accordance
				with this Privacy Policy and no transfer of your data will take place to an organization or a country
				unless
				there are reasonable controls in place including the security of your data.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">8. YOUR RIGHTS</span>
		<ol type="I">
			<li>
				You can always choose not to provide the requested information to us for the purposes mentioned in
				this
				Privacy Policy, it may however result in You not availing certain features if, or the entirety, of our
				Services.
			</li>
			<li>
				You have the following rights:
				<ul>
					<li>
						access, confirm, and review Personal Data you may have provided;
					</li>
					<li>
						correct Personal Information that may be inaccurate or irrelevant;
					</li>
					<li>
						update and erasure of your Personal Data from the Platform;
					</li>
					<li>
						redress your grievances, if any;
					</li>
					<li>
						withdraw your consent, in which case we will cease processing your personal data obtained
						based
						on
						your
						consent
					</li>
					<li>
						right to appoint a nominee to exercise the rights on your behalf in the event of your
						death
						or
						incapacity
						to exercise your rights.
					</li>
				</ul>
			</li>
			<li>
				In order to exercise these rights or raise your concerns (if any) related to our handling of your
				personal
				data, please contact us at the email address provided in Clause 3.3 above.
			</li>
			<li>
				If you withdraw/object your consent, our use of your information before you withdrew/objected shall
				continue to be lawful.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">9. APPLICATIONS USED</span>
		<ol type="I">
			<li>
				You may be availing our Services for using third party mobile applications, which are not operated
				by us.
				We strongly advise you to review the privacy policy of every mobile application which you may use.
			</li>
			<li>
				We have no control over and assume no responsibility for the content, privacy policies or practices
				of any
				third-party mobile applications or services.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">10. CHILDREN’S PRIVACY</span>
		<ol type="I">
			<li>
				Our Platform and Services are not meant for use by children and we knowingly do not collect or solicit
				Personal Information from anyone under the age of 18. If you are under 18, please do not attempt to
				register
				for
				the Services or send any personal information about yourself to If you are under 18, please do not
				attempt
				to
				register for the Services or send any personal information about yourself to us. If we learn that we
				have
				collected Information from/of a person under the age of 18, we shall take steps to remove such
				Information
				from
				our servers as quickly as possible. If you believe that a person under age 18 may have provided us with
				Personal
				Information, please write to us at the email address – <span
					style="font-weight: bold;">Support@talentgridnow.com</span>.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">11. CONTROL THE COLLECTION OR USE OF THE INFORMATION</span>
		<ol type="I">
			<li>
				If you have any reservations, constraints or apprehensions regarding the access to, collection,
				storage,
				sharing or any other use of the Information which you have provided to us, you may withdraw your consent
				by
				writing to us on the email address – Support@talentgridnow.com.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">12. RETENTION OF INFORMATION</span>
		<ol type="I">
			<li>
				All Information provided by you, save and except upon withdrawal or termination, shall be retained
				in
				locations outside the direct control of Company (for instance, on servers or databases co-locates with
				hosting
				providers). We will delete Information based on a request received from you within a reasonable period
				and
				latest within 180 (one hundred eighty) days of receiving a deletion request. However, we may retain such
				portion
				of Information and for such periods as may be required under Applicable Law. Notwithstanding anything
				contained
				herein, Company may retain data after account deletion for compliance with any legal obligation.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">13. COOKIES AND OTHER TRACKING TECHNOLOGIES</span>
		<br />
		Our Platform may utilize “cookies” and other technical Information. “Cookies” are a small text file consisting
		of alphanumeric numbers used to collect the Information about your activity on the Platform. The technical
		Information helps us analyse web traffic and helps you by customizing the Platform to your preferences. Cookies
		in no way gives us access to your computer or mobile device. In relation to Cookies, you can deny access to the
		installation of the Cookies by modifying the settings on your web browser, however, this may prevent you from
		taking full advantage of the Platform. Our use of Cookies and technical Information allows us to improve
		Platform and your experience of Platform and Services. We may also analyse technical Information that does not
		contain Personal Information for trends and statistics.
	</div>
	<div>
		<br />
		<span style="font-weight: bold;">14. THIRD PARTY SERVICES</span>
		<br />

		We may use your Information to send you promotional Information about third parties which, we think you may find
		interesting, if you tell us that you wish this to happen. We shall not be responsible for any disclosure of
		Information due to unauthorized third-party access or other acts of third parties or acts or omissions beyond
		our reasonable control and you agree that you will not hold us responsible for any breach of security unless
		such breach has been caused as a direct result of our negligence or wilful default.
		Once you leave the Platform, we are not liable for any use/ storage/ processing/ collection of your information
		obtained by any third-party websites or provided by you to these third-parties. Such entities and their
		respective websites/platforms may be governed by their own “Privacy Policy” and “Terms of Service”, which are
		beyond our control.
	</div>
	<div>
		<br />
		<span style="font-weight: bold;">15. DATA SECURITY</span>
		<br />

		You agree and accept that your Information may be stored in third-party cloud service infrastructure providers.
		While all reasonable attempts have been taken from our end to ensure the safe and secure storage of your data,
		we shall not be liable for any data breach on the part of the third-party cloud service infrastructure provider
		that was beyond our control. In addition to the security measures put in place by the third-party cloud service
		infrastructure provider for safe and secure storage of your Information, we use certain physical, managerial,
		technical or operational safeguards as per industry standards and established best practices to protect the
		Information we collect. We use reasonable security practices and procedures and use secure servers as mandated
		under applicable laws for the protection of your Information. We review our Information collection, storage, and
		processing practices, including physical security measures to guard against unauthorized access to systems.
		However, as effective as these measures are, no security system is impenetrable. We cannot guarantee the
		security of our database, nor can we guarantee that the Information you supply will not be intercepted while
		being transmitted to us over the internet. You accept the inherent security implications of data transmission
		over the internet and the internet cannot always be guaranteed as completely secure. Therefore, your use of the
		Platform will be at your own risk. If you have any concerns, please feel free to contact us by emailing us at –
		<span style="font-weight: bold;">Support@talentgridnow.com</span>.
	</div>
	<div>
		<br />
		<span style="font-weight: bold;">16. CHANGES AND UPDATES TO POLICY</span>
		<br />

		We may modify or revise the Privacy Policy from time to time and shall accordingly notify you of any changes to
		the Privacy Policy by posting the revised Privacy Policy on the Platform with an updated date of revision. We
		shall endeavour to review, revise, update, modify, amend or correct the Privacy Policy on a regular and routine
		basis, especially whenever a significant update is made to the technology employed by us. You must periodically
		review the Privacy Policy for the latest information on our privacy practices. In the event you continue to use
		the Platform and our services after any update in the Privacy Policy, your use of the Platform shall be
		automatically subject to such updated privacy policy. Your continued usage of Services or access of the Platform
		post any amendment would deem to mean that you accept and agree to the revised Privacy Policy. Further, we
		retain the right at any time to deny or suspend access to all, or any part of, the service to anyone who we
		reasonably believe has violated any provision of this Privacy Policy.
	</div>
	<div>
		<br />
		<span style="font-weight: bold;">17. DISCREPANCIES AND GRIEVANCES WITH COMPANY</span>
		<br />

		In case of any discrepancy or grievance with respect to all or any Information shared with Company, please feel
		free to contact our Grievance Officer:
		<br />
		Attention: <span style="font-weight: bold;">Grievance officer</span>
		<br />
		Email ID: <span style="font-weight: bold;">Support@talentgridnow.com</span>
		<br />
		Address: Flat 001, Fort St Johns Apartment, 21 Rukmini Colony, Sivanchetti Gardens, Bengaluru, India 560042
		<br />
		<br />
		We will acknowledge each grievance that is received within 4 (four) hours and put our best efforts to redress
		the grievances of the User expeditiously within 180 (one hundred eighty) days from the date of receipt of the
		grievance. The User agrees and acknowledges that the Company shall address and attempt to resolve the complaint
		received in accordance with the standard policies and procedures adopted by the Company, the User’s
		disapproval/discontent with the outcome/mode of redressal shall not be deemed to mean non-redressal of the
		grievance by the Company. Any suggestions by Company regarding use of the Service shall not be construed as a
		warranty.
		<br />
		<br />
		Please feel free to reach out to us by e-mail at Support@talentgridnow.com in case of any concerns, grievances, or
		questions relating to our privacy or data related practices.
	</div>
</div>
	`;

	return (
		<SafeAreaView style={{ flex: 1, backgroundColor: theme.colors.black }}>
			<Header name="Privacy Policy" />
			<ScrollView>
				<RenderHtml
					systemFonts={[...defaultSystemFonts, theme.fontFamily.cgRegular, theme.fontFamily.cgBold]}
					contentWidth={CONSTANTS.screenWidth}
					source={{ html: source }}
					tagsStyles={{
						div: {
							color: 'whitesmoke',
							fontSize: theme.fontSize.typographyMd,
							paddingHorizontal: theme.padding.xs,
							fontFamily: theme.fontFamily.cgRegular,
						},
						p: {
							marginBottom: 12,
							fontFamily: theme.fontFamily.cgRegular,
						},
						strong: {
							fontFamily: theme.fontFamily.cgBold,
						},
					}}
				/>
			</ScrollView>
		</SafeAreaView>
	);
}

const stylesheet = StyleSheet.create({
	padding: {
		paddingTop: Platform.OS === 'ios' ? 50 : 0,
		backgroundColor: 'black',
	},
	container: {
		flex: 1,
		backgroundColor: 'black',
	},
});
