import { Platform, SafeAreaView, ScrollView, StyleSheet } from 'react-native';
import { useStyles } from 'react-native-unistyles';
import Header from '@components/Header';
import RenderHtml, { defaultSystemFonts } from 'react-native-render-html';
import CONSTANTS from '@constants/constants';

export default function TNC() {
	const { styles, theme } = useStyles(stylesheet);
	const source = `
<div style="color: whitesmoke; font-size: 16px; padding: 0 16px; font-family: CabinetGrotesk-Regular;">
	<p style="font-weight: bold">Last updated: 1st January 2025</p>

	<p style="font-weight: bold">This document is an electronic record in terms of the Indian Contract Act 1872; the Information
		Technology Act 2000, the rules made thereunder; and the amended provisions pertaining to the electronic records
		in various other statutes as amended by the Information Technology Act, 2000. This electronic record is
		generated by a computer system and does not require any physical or digital signatures.</p>

	<div>
		Talent Grid Private Limited , having its registered office at No. 1605, 11th Main, Off Jeevan Bhima Nagar Main Road, HAL Stage 3, Bengaluru, Karnataka,560008 (“<span style="font-weight: bold">Company</span>” or “<span
			style="font-weight: bold">we</span>” or “<span style="font-weight: bold">us</span>” or “<span style="font-weight: bold">our</span>”), is the owner
		of the website domain at <span style="font-weight: bold">https://talentgridnow.com</span> and all other variations of the same and
		as mobile applications available on the Google Play store, App Store as “Talent Grid”, (collectively referred to
		as “<span style="font-weight: bold">Platform</span>”)
	</div>
	<br />
	<div>
	The Company requests you and any other users of the Platform (individually, a
	<span style="font-weight: bold">User</span>, “you” and collectively,
	<span style="font-weight: bold">Users</span>) to carefully go through these terms & conditions (“<span style="font-weight: bold">Terms
		of Use</span>” or “<span style="font-weight: bold">Agreement</span>” or “<span
		style="font-weight: bold">TOU</span>” or “<span style="font-weight: bold">Terms</span>”)
	prior to accessing the Platform or availing Services (as defined below) using the Platform.

	If a User continues to browse and use the Platform to avail Services, the User irrevocably and unconditionally agrees to comply
	with, abide by, and be bound by all these obligations as stipulated in this TOU, which, together with our
	privacy policy available at 
	<a href="https://talentgridnow.com/terms-and-conditions" target="_blank" style="font-weight: bold; text-decoration: underline; color: #0000EE;">
		https://talentgridnow.com/terms-and-conditions
	</a> (“<span style="font-weight: bold">Privacy Policy</span>”), and any other applicable
	policies referred to herein or made available on the Platform (collectively referred to as “<span
		style="font-weight: bold">Terms and Conditions</span>”).

	The Terms and Conditions shall govern the Company’s relationship with the User in relation to the usage of the
	Platform. These Terms and Conditions supersede all previous oral or written terms and conditions (if any)
	communicated to the User and shall act as a binding agreement between the Company and the User.
</div>



	<p style="font-weight: bold">IF YOU DO NOT AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS CAPTURED IN THE TOS, PLEASE DO NOT USE
		THE PORTAL OR
		SERVICES.</p>
	<div>
		<span style="font-weight: bold">1. Definitions</span>

		"<span style="font-weight: bold">Service(s)</span>" means the functions, features, tools, applications, products, software,
		data feeds, Content, User
		Submissions, and services available on the Platform, including talent management, production management,
		accounting services provided through third parties such as invoices generation and tax returns management, and
		other allied film production related services.
	</div>
	<div>
		<span style="font-weight: bold"><br />2. Updation of Terms and Conditions</span>
		<br />
		Your use of the Platform is subject to the Terms and Conditions, which may be updated, amended, modified, or
		revised by us from time to time. To ensure that you are aware of any additions, revisions, amendments, or
		modifications that we may have made to these Terms and Conditions, it is important for you to refer to the Terms
		and Conditions from time to time. The updated Terms and Conditions shall be effective immediately and shall
		supersede these. We shall not be under an obligation to notify you of any changes to the Terms and Conditions.
		You shall be solely responsible for reviewing the Terms and Conditions from time to time for any modifications.
		If you continue to use the Platform and/or Services after the updated Terms and Conditions have been published,
		it shall be deemed that you have read and understood and accept the updated Terms and Conditions. Any reference
		to Terms of Use, TOU, Agreement made herein shall refer to the latest version of the Terms of Use.
	</div>
	<div>
		<span style="font-weight: bold"><br />3. Service(s) provided to Users</span>
		<ol type="a">
			<li>
				We provide a Platform that offer the following services:
				<ul>
					<li>Talent management.</li>
					<li>Production management.</li>
					<li>Accounting services provided through third parties, such as invoices generation and tax returns
						management.</li>
					<li>Location / Studio hire services</li>
					<li>Talent hire services</li>
					<li>Other allied film production related services.</li>
				</ul>
				Collectively, these offerings constitute the "Services,"
			</li>
			<br />
			<li>
				The Platform offer various content types, including text, graphics, photos, news, articles, audio
				visual
				content, (collectively, “Content”) and interactive platforms such as forums and chat rooms. Users may
				need
				to
				create an account for specific access. All content, whether available with or without payment or
				subscription,
				may include facts, views, opinions, and recommendations of or concerning individuals, organizations, or
				projects
				not affiliated with the Company. Company does not guarantee the accuracy, completeness, or timeliness
				of, or
				otherwise endorse, these facts, views, opinions, or recommendations. Users accessing and using Content
				do so
				at
				their own risk and discretion
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold">4. Eligibility<br /></span>

		By using Platform, you affirm that you are at least 18 years of age and are fully able and competent to
		enter
		into the terms, conditions, obligations, affirmations, representations, warranties set forth in the Terms
		and
		Conditions, and to abide by and comply with the terms stated therein. Registration on the Platform is
		available
		only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are
		"incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors,
		un-discharged
		insolvents, or person with unsound mind etc. are not eligible to use the Platform. By accessing the Platform
		or
		by accessing any of the Services on any other authorized device, it is deemed that the User has read and
		understood and accepted these TOU. If you will be using the Services on behalf of an organization, you agree
		to
		these Terms on behalf of that organization and you represent that you have the authority to do so.
	</div>
	<div>
		<span style="font-weight: bold"><br />5. User Account Registration</span>

		<ol type="I">
			<li>
				Any individual who is at least 18 years of age may create an Account by providing the necessary details to
				avail the Services. In order to use the Platform, you have to create an account (“<span
					style="font-weight: bold">Account</span>”) and subscribe to
				one of our existing Subscription plans (“<span style="font-weight: bold">Plan</span>”) You shall provide true and
				accurate information while
				creating Your Account. The information collected while creating your Account will be governed by our Privacy
				Policy. 
			</li>
			<li>
			At the time of sign up, you will be prompted to select your profession and based on your input
you will either be given a Talent Account or Studio Account.
			<br />
		<div><b>(a) Talent Account:</b></div>
		<ul>
			<li>Upon being assigned a Talent Account, you will gain access to features designed
			specifically for individuals offering their personal skills and services, such as acting, writing,
				music production, and other creative services. A Talent Account enables you to showcase
			your work, apply for relevant opportunities, and connect with producers or studios seeking
				talent.</li>
		</ul>
		<br />
		<div>Features and Functionalities of a Talent Account:</div>
		<ol type="i">
			<li><b>Talent Profile Creation and Management:</b>
				<ul>
					<li>
						As a Talent Account holder, you can create a detailed profile showcasing your
						skills, experience, and portfolio. This may include uploading a professional
						resume, videos, images, or other work samples that highlight your talents.
					</li>
					<li>
						Your profile can be customized to emphasize your specialties (e.g., acting,
		voice-over, music, etc.) and updated regularly to reflect new work or
		achievements.
					</li>
				</ul>
			</li>
			<li>
				<b>Opportunities and Job Listings:</b>
				You can browse and apply for opportunities
posted on the Platform. These opportunities can range from specific project roles to
ongoing talent requirements. You may receive invitations to apply for roles directly
based on your skills, experience, or past project work.
			</li>
			<li>
			<b>Availability and Scheduling:</b> You can manage your availability, allowing producers
or studios to book you for specific roles or projects. This includes managing your
calendar, setting working hours, and updating your availability as needed. You may
also receive notifications about potential opportunities matching your skills and
schedule.
			</li>
			<li>
			<b>Payment and Contract Management:</b> Manage your payment details, and track
earnings related to the services you offer. The Platform allows you to view your
payment history, manage invoicing, and ensure timely payment for services
rendered.
			</li>
			<li>
			<b>Talent Reviews and Ratings:</b> Producers and studios may leave feedback after
working with you. Positive reviews and ratings will enhance your reputation, helping
you gain more opportunities on the Platform. You may also leave feedback for
producers or studios, which will be available for others to see.
			</li>
			<li>
	<b>Networking and Collaboration:</b> As a Talent Account holder, you will have access to
a network of producers, studios, and other talent, allowing you to build connections
and collaborate on larger projects or gain exposure to new opportunities. Participate
in community forums or events to expand your professional network and stay up-to-
date with industry trends.
			</li>
			<li>
			<b>Training and Development Opportunities:</b> You may have access to professional
development resources, such as workshops, training sessions, or webinars hosted
by industry professionals. These resources can help you improve your skills and stay
competitive in the market.
			</li>
			<li>
			<b>Visibility and Promotion Tools:</b> You can take advantage of the Platform’s
promotional tools to increase your visibility to producers and studios. This may
include featured profile listings, social media integration, or spotlight placements on
the Platform.
			</li>
		</ol>
		<div><b>(b) Studio Account:</b></div>
		<div>
		Upon being assigned a Studio Account, you will gain access to features designed for those
offering studio-related services through the Platform. A Studio Account allows you to list and
offer your studio facilities and services to user having Producer Account who are seeking
production spaces or related services.
		</div>
		<br/>
		<div><b>Features and Functionalities of a Studio Account:</b></div>
		<ol type="I">
			<li>
				Studio Listings and Management: As a Studio Account holder, you can create and
	manage listings for your studio space, including details such as studio size, equipment
	available, location, availability schedules, and pricing. Your listing can be customized
	with high-quality images, videos, and descriptions of your studio facilities to attract
	producers.
			</li>
			<li>
			Studio Booking and Availability: Producers can browse and book your studio through
the Platform. You can manage booking requests, track studio usage through the
platform’s calendar, etc. You can also put pricing models for your studios, such as
hourly, daily, or project-based rates, to cater to various production needs.
			</li>
			<li>
			Collaboration with Producers: Once a booking is confirmed, you will be able to
collaborate with producers and talents on the project. This includes providing access to
your studio facilities, coordinating with production teams, and offering additional
services like technical support or equipment rentals.
			</li>
			<li>
			Access to Talent-Specific Services: As a Studio Account holder, you can offer your
studio to producers who may also need talent for their projects. Through the Platform,
you can connect with talent, offer joint services, or collaborate on specific projects that
require both studio space and talent.
			</li>
			<li>
			Studio Reviews and Ratings: After each booking, producers and talent can leave
reviews or ratings for your studio. Positive feedback can help you build a strong
reputation on the Platform and attract more clients.
			</li>
			<li>
			Marketing and Promotion Tools: You may access promotional tools to enhance visibility
for your studio. This can include featured listings, discounted rates, or targeted
advertising to producers in need of studio spaces.
			</li>
		</ol>
		</li>
		<li>
		<b>Conversion of Talent to Producer Account:</b>
		<br />
If you have been assigned a Talent Account and wish to convert it to a Producer Account, you
must request the conversion by sending an email to the Company at &lt;&lt;&gt;&gt;. Your request will be
reviewed, and the Company will assess whether to grant you the right to convert your Account.
	Once the Company approves your request, you will be granted access to Producer Account
features. After this conversion, you will be able to manage both a Talent Account and a Producer
Account within a single user profile.
		</li>
		<li>
		<b>Managing Multiple Accounts:</b>
		<br />
After receiving approval for the conversion, your Account will be upgraded to include both Talent
and Producer roles. You will be able to seamlessly switch between the two roles within your
account. Switching between the Talent and Producer accounts will not require separate logins,
and you can access both roles from your primary user interface. This flexibility allows you to
manage your activities as both a Talent and a Producer on the Platform.
		</li>
		<li>
		<b>Account Responsibility and Maintenance:</b>
		<br />
You are responsible for maintaining the confidentiality of your login credentials and are fully
responsible for all activities that occur under your Account. You may create an Account by using
your email ID/phone number. Post entering your details (email ID/phone number) in the Platform,
one-time verification shall be conducted by the Company. Post such verification the Account shall
be created.
		</li>
	</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />6. Platform License</span>
		<ol type="I">
			<li>
				Subject to your compliance with the TOU, Company grants you a limited, non-exclusive,
				non-transferable
				license: (i) to view, download and print any content of Platform solely for your personal and
				non-commercial
				purposes; and (ii) to access, modify,and download content, to which you are permitted access solely
				for
				your
				internal purpose use. You have no right to sublicense the license rights granted herein.
			</li>
			<li>
				You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license,
				sell,
				transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the
				Platform
				and Services, except as expressly permitted in the TOU. No licenses or rights are granted to you by
				implication or otherwise under any intellectual property rights owned or controlled by Company or
				its
				licensors, except for the licenses and rights expressly granted in the TOU. The Platform and the
				intellectual property rights vested therein is owned by Company.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />7. Proprietary Rights</span>
		<ol type="I">
			<li>
				Ownership and Content: Company is the rightful owner, operator, licenser, and provider of the
				Platform.
				Users explicitly acknowledge and agree that Company, along with its licensors, holds all rights,
				titles,
				and
				interests to all current and future content, applications, software, and materials available on the
				Platform. This includes but is not limited to audiovisual content, text, images, graphics, videos,
				page
				headers, and the overall arrangement and compilation of Content. Such ownership encompasses patent
				rights,
				copyright rights, trademark rights, trade secret rights, and other intellectual property rights
				recognized
				globally, except for User provided content as defined below.
			</li>
			<li>
				Limitation of Rights: Unless explicitly stated in these Terms of Use or provided in writing by
				Company,
				Users are not granted any rights, either implied, estoppel, or otherwise, to the Platform or their
				Contents.
				All rights not expressly granted herein are reserved by Company.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />8. Use of Your Information and Content and other content displayed on the
			Platform</span>
		<ol type="I">
			<li>
				If You create, transmit, submit, display or otherwise make available any information while using the
				Services, you may provide only information that you own or have the right to use. We may only use
				the
				information you provide as permitted by our Privacy Policy and applicable law. For example, we will
				never
				share your personally identifiable information without your prior permission. Please closely review
				our
				Privacy Policy for more information regarding how we use and disclose your personal information. Our
				Privacy
				Policy is hereby incorporated into these Terms of Use by this reference.
			</li>
			<li>
				We reserve the right to maintain, delete or destroy all information and materials posted or uploaded
				through the Services, pursuant to our internal record retention and/or destruction policies. We
				(may/may
				not) make use of third-party cloud services providers or use our own service infrastructure for
				hosting
				the
				servers and databases. While we make commercially reasonable efforts to ensure that the data stored
				on
				our
				servers is persistent and always available to the User, we will not be responsible in the event of
				failure
				of the third-party servers or any other factors outside our reasonable control that may cause the
				User’s
				data to be permanently deleted, irretrievable, or temporarily inaccessible.
			</li>
			<li>
				While we strive to maintain the accuracy and reliability of the data presented on our platform, we
understand that inconsistencies or errors may occasionally occur. We encourage you to promptly
notify us of any discrepancies or inaccuracies you encounter, and we will make every reasonable
effort to address and correct such issues. However, by using our platform, you acknowledge that
this process is limited to best efforts only, and you agree that such inconsistencies or errors do
not grant you any right to bring a legal claim or lawsuit against us.
			</li>
			<li>
				You acknowledge and agree that we may preserve your information and may also disclose your related
				information if required to do so by law; or in the good faith belief that such preservation or
				disclosure is
				reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b)
				enforce
				these TOS; (c) respond to claims that any of your usage of the Platform violates the rights of third
				parties; (d) detect, prevent, or otherwise address fraud, security or technical issues; or (e)
				protect
				the
				rights, property, or personal safety of the Platform, its users, or the public.
			</li>
			<li>
				You agree to only provide content or information that does not violate the law nor anyone’s rights
				(including intellectual property rights). You also agree that your Account information will be
				truthful.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />9. Third Party Services</span>
		<ol type="I">
			<li>
				While availing Services, Users may connect with third-party service providers. The Company is not
				responsible for, and does not endorse, any third-party services mentioned on the Platform. It is
				hereby
				stated that Company shall in no way be responsible for any acts or omissions of third parties. Any
				transaction, dealings or communication otherwise that the User may have with such third parties are
				at
				the
				User’s own risk and we make no warranties, express or implied regarding the quality or suitability
				of
				the
				services or products of such third-party vendors. You may be redirected to a third-party website
				upon
				clicking on such links, these websites will be governed by its privacy policy and terms of use. We
				shall
				not
				be responsible for any transaction or dissemination of information that may take place while
				accessing
				these
				third-party websites.
			</li>
			<li>
				Third-Party Intellectual Property: Intellectual property rights, including trademarks, logos,
				content,
				and other proprietary materials belonging to third parties, remain the sole property of those
				respective
				third parties and are protected under applicable copyright, trademark, and other intellectual
				property
				laws
				and treaties. Users must respect these rights and acknowledge that they have no claim or right to
				such
				third-party intellectual property. The use of third-party software or services accessed via the
				Websites
				is
				subject to the terms and conditions set forth in the respective third-party license agreements.
				Users
				must
				seek remedies or rights enforcement exclusively from the relevant third party, not from Backstage.
				Third Party content: The Company shall not be liable for the accuracy, legality or content of any
				third-party content that ay e accessible through our Platform. Such content is provided by
				third-party
				and
				does not represent the views or opinion of the Company. User accessing third-party content do so at
				their
				own risk. Any claim regarding third party content, including but not limited to claims of
				infringement
				of
				intellectual property rights, must be addressed directly to the third party responsible for such
				content.
				The Company does not waive any intellectual property rights by providing the access to third party
				content.
				The Company acknowledges that such third party content are publicly available content and it does
				not
				claim
				any ownership of such third party content. In the event the third party content is proven to belong
				to a
				third party after providing documentary evidence to the grievances officer of the Company, the
				Company
				will
				promptly remove such content.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />10. Rules and Conduct</span>
		<ol type="I">
			<li>
				As a condition of use, you promise not to use the Platform for any purpose that is prohibited by the
				Terms of Use; or other rules or policies implemented by us from time to time; or in violation of any
				applicable laws.
			</li>
			<li>
				By way of example, and not as a limitation, you shall not (and shall not permit any third party to)
				take
				any action (including without limitation host, display, upload, modify, publish, transmit, store,
				update
				or
				sharing of information) that:
				(i) would constitute a violation of any applicable law, rule or regulation or
				belongs to another person;
				(ii) infringes on any intellectual property or other right of any other person or
				entity;
				(iii) is threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent; or
				(iv) impersonates any person or entity
				(v) deceives or misleads the addressee about the origin of the message or
				knowingly and intentionally communicates any information which is patently false or misleading in
				nature
				but
				may reasonably be perceived as a fact,
				(vi) contains software virus or any other computer code, file or
				program designed to interrupt, destroy or limit the functionality of any computer resource or (vii)
				is
				patently false and untrue, and is written or published in any form, with the intent to mislead or
				harass
				a
				person, entity or agency for financial gain or to cause any injury to any person. The Company
				reserves
				the
				right to disable any Account from the Platform at any time for any reason (including, but not
				limited
				to,
				upon receipt of claims or allegations from third parties or authorities; or if Company is concerned
				that
				You
				may have violated the Terms of Use), or for no reason at all with or without notice to the
				User/Users.
			</li>
			<li>
				Additionally, you shall not share any information that:
				(i) may be harmful to minors or children
				below
				the age of 18 (eighteen) years;
				(ii) threatens the unity, integrity, defence, security or sovereignty of
				the
				country, friendly relations with foreign states or public order or causes incitement to the
				commission
				of
				any cognisable offence or prevents investigation of any offence or is insulting any other nation;
				and
				(iii)
				is invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging,
				relating
				or
				encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
				(iv) harms
				minors in
				any manner;
				(v) infringes any patent, trademark, copyright or other proprietary rights;
				(vi) violates
				any
				laws for time being.
			</li>
			<li>
				Furthermore, you shall not (directly or indirectly):
				(i) take any action that imposes or may impose
				an
				unreasonable or disproportionately large load on Company’s (or its third party providers’)
				infrastructure;
				(ii) interfere or attempt to interfere with the proper working of the Platform or any activities
				conducted
				on the Platform;
				(iii) bypass any measures we may use to prevent or restrict access to the Platform (or
				parts thereof);
				(iv) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive
				any
				source code or underlying ideas or algorithms of any part of the Platform, except to the limited
				extent
				applicable laws specifically prohibit such restriction;
				(v) modify, translate, or otherwise create
				derivative works of any part of the Platform; or
				(vi) copy, rent, lease, distribute, or otherwise
				transfer
				any or all of the rights that you receive hereunder.
			</li>
			<li>
				You will not access the Platform, and/or its services, or the personal information of other Users,
				available on the Platform in order to build a similar or competitive website, product, or service.
			</li>
			<li>
				If are an Individual, you will not access the Platform and/or its services for the purpose of
				hiring,
				recruiting or inviting any other User to attend any program, event, function, seminar, conference,
				talk,
				etc.
			</li>
			<li>
				You agree to immediately notify us of any unauthorised use, or suspected unauthorized use of Your
				Account, or any other breach of security, in relation to Your personal information on the Platform.
			</li>
			<li>
				One Account shall not be used by more than one User. Any use of an Account by a third-party would
				deem
				to be unauthorised usage. The Company reserves the right to disable any such Account from the
				Platform.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />11. Alerts Provided by The Company</span>
		<ol type="I">
			<li>
				The Company provides you with multiple automatic alerts while providing Services.
			</li>
			<li>
				You understand and agree that any alerts provided to you through the Platform may be delayed or
				prevented by
				a variety of factors. We will do our best to provide alerts in a timely manner with accurate
				information.
				However, we neither guarantee the delivery nor the accuracy of the content of any alert. You also agree
				that we
				shall not be liable for any delays, failure to deliver, or misdirected delivery of any alert; for any
				errors in
				the content of an alert; or for any actions taken or not taken by you or any third party in reliance on
				an
				alert.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />12. Contact You</span>
		You agree that we may contact you through telephone, email, SMS, or any other means of communication for the
		purpose of:
		<ol type="I">
			<li>
				Obtaining feedback in relation to Platform or our Services;
			</li>
			<li>
				Obtaining feedback in relation to any other Users listed on the Platform;
			</li>
			<li>
				Any events or initiatives that you may be interested in as part of the community of users
			</li>
			<li>
				Resolving any complaints, information, or queries by other Users regarding your critical content;
			</li>
			<li>
				For sales related purposes;
			</li>
			<li>
				To inform you of our service offerings and new features; and
			</li>
			<li>
				You agree to provide your fullest co-operation further to such communication by Company.

				By submitting suggestions or other feedback regarding our Services/Platform, you agree that we can use
				and
				share
				such feedback for any purpose without any compensation to you and we are under no obligation to keep
				such
				feedback confidential.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold;">13. Account Ownership and Editing Rights<br /></span>
		We ensure easy access to the Users by providing an option to update your Account information. We reserve the
		right to moderate the changes or updates requested by you and we shall take an independent decision whether to
		publish or reject the requests submitted for the respective changes or updates in your Account. You hereby
		represent and warrant that you are fully entitled, under applicable law, to provide information as part of your
		Account or otherwise while using our Services, and that no such information breaches any third-party rights,
		including intellectual property rights and applicable data protection laws. Upon becoming aware of a breach of
		the foregoing representation, we may modify or delete parts of your Account information at our sole discretion
		with or without notice to you.
		Excluding your Account information and the User Materials you acknowledge that the Platform, the Services, and
		all the intellectual property rights, including copyrights, patents, trademarks, designs, and trade secrets in
		relation to the above are solely owned by us.
	</div>
	<div>
		<span style="font-weight: bold;"><br />14. Rights and Obligation relating to the usage of the Platform</span>
		<br />
		Users shall be prohibited from carrying out the any illegal acts in the Platform including but not limited to
		acts mentioned below:
		<ol type="I">
			<li>
				violating or attempting to violate the integrity or security of the Platform;
			</li>
			<li>
				transmitting any information on or through the Platform that is disruptive or competitive to the
				provision
				of our Services;
			</li>
			<li>
				intentionally submitting on the Platform any incomplete, false or inaccurate information;
			</li>
			<li>
				making any unsolicited communications to other Users;
			</li>
			<li>
				using any engine, software, tool, agent or other device or mechanism (such as spiders, robots,
				avatars or
				intelligent agents) to navigate or search the Platform;
			</li>
			<li>
				circumventing or disabling any digital rights management, usage rules, or other security features of the
				Platform.
			</li>
			<li>
				Any unlawful activities in the Platform which are prohibited by laws of India.
			</li>
		</ol>

		The Company shall, upon obtaining knowledge by itself or been brought to actual knowledge by an affected person
		in writing or through email signed with electronic signature about any such information as mentioned above, be
		entitled to disable such information that is in contravention of this Clause. We shall also be entitled to
		preserve such information and associated records for at least 90 (ninety) days for production to governmental
		authorities for investigation purposes. In case of non-compliance with any applicable laws, rules or
		regulations, or the Agreement (including the Privacy Policy) by a User, we shall have the right to immediately
		terminate your access or usage rights to the Platform and Services and to remove non-compliant information from
		the Platform.

		We may disclose or transfer User-generated information to our affiliates or governmental authorities in such
		manner as permitted or required by applicable law, and you hereby consent to such transfer. In accordance with
		the applicable laws, we shall transfer sensitive personal data or information including any information, to any
		other body corporate or a person in India, or located in any other country, that ensures the same level of data
		protection that is adhered to by us, only if such transfer is necessary for the performance of the lawful
		contract between Company or any person on its behalf and the User or where the User has consented to data
		transfer.
	</div>
	<div>
		<span style="font-weight: bold;"><br /><b>15. Company and User Materials</b></span>
		<br />
		While rendering Services, Company directly or through its representatives, may provide Users with certain
		materials relevant to the Services, which may be in the form of audio, video, written and oral content (“<span
			style="font-weight: bold">Company
			Materials</span>”). Company Materials shall be the exclusive property of the Company. User hereby agrees and
		acknowledges that he/she shall ensure that the Company Materials are not shared with any third party, without
		Company’s written consent and any breach of such nature shall cause financial and irreparable injury to Company.
		Company hereby provides User with a revocable, non-exclusive, non-transferable, non-sublicensable, limited
		license to use the Company Materials solely for its personal purpose and not for any commercial use. While
		availing Services, User may submit various materials to Company in the form of audio/video/written content
		(“<span style="font-weight: bold">User Materials</span>”). User hereby provides Company with an exclusive, transferrable,
		perpetual and irrevocable
		license to use the User Materials for its use. User hereby agrees and acknowledges that User Materials shall not
		infringe any intellectual property rights of third party and shall be responsible for any claims arising out of
		infringement. Additionally, all User Materials provided will be used by the Company for analytics to understand
		the User and the market, and hereby the Company reserves its right to revise and enhance the Platform and the
		Services provided the User.
	</div>
	<div>
		<span style="font-weight: bold"><br />16. Modification</span>
		<br />
		We reserve the right, at any time and in with sole discretion, to change, modify, or amend the Platform (in
		whole, or in part) or any of its Services (in whole, or in part), in compliance with the applicable legal and
		regulatory framework. You agree that We will not be liable to You for any change, modification or amendment of
		the Platform or its Services, or any part thereof.
	</div>
	<div>
		<span style="font-weight: bold"><br />17. Support</span>
		<br />
		The Company offers an email and in-app-based support system. In case you require any assistance or support, you
		may access support resources or contact our support by emailing at it- <span
			style="font-weight: bold">Cs@talentgridnow.com</span> or use the “Support”
		function on the Platform.

		The User agrees and acknowledges that the Company shall address and attempt to resolve the complaint received in
		accordance with the standard policies and procedures adopted by the Company, the User’s disapproval/discontent
		with the outcome/mode of redressal shall not be deemed to mean non-redressal of the complaint by the Company.
		Any suggestions by Company regarding use of the Service shall not be construed as a warranty.

		In furtherance of the Consumer Protection Act 2019 (“<span style="font-weight: bold">Consumer Protection Act</span>”) and the
		Consumer Protection (E-
		Commerce) Rules 2020 (“<span style="font-weight: bold">E-Commerce Rules</span>”) a nodal officer is appointed to ensure
		compliance with the Consumer
		Protection Act and the E-Commerce Rules.

		The details of the grievance officer to which consumer grievances can be redressed are as follows;

		<span style="font-weight: bold">Name: Grievance officer</span>
		<span style="font-weight: bold">Contact Details: Support@talentgridnow.com</span>
		<span style="font-weight: bold">Designation of such officer: Senior Grievance officer</span>

		The Company shall revert to every complaint within 48 hours of receipt of the complaint. Further, the Company
		shall take best possible efforts to redress the complaint within 180 days of receipt of the complaint. Any
		suggestions by Company regarding use of the Services shall not be construed as a warranty.
		The User agrees and acknowledges that the Company shall address and attempt to resolve the complaint received in
		accordance with the standard policies and procedures adopted by the Company, the User’s disapproval/discontent
		with the outcome/mode of redressal shall not be deemed to mean non-redressal of the complaint by the Company.
		Any suggestions by Company regarding use of the Service shall not be construed as a warranty
	</div>
	<div>
		<span style="font-weight: bold"><br />18. Termination</span>
		<ol type="I">
			<li>
				Termination/ Suspension of Services:
				We have the right to temporarily suspend access to the whole or any part of the Services for any reason
				whatsoever (including but not limited to technical/operational reasons) and shall be under no liability
				to
				you
				in such an event. Further, we may, but shall not be obliged to, give You notice of any interruption of
				access to
				the Service. We may temporarily suspend access to the whole or any part of the Services for
				pre-scheduled
				maintenance. The intent to temporarily suspend access for pre-scheduled maintenance shall be
				communicated to
				you
				48 hours in advance via email to the email id provided by you upon creation of your Account. If you
				choose
				to
				access the Platform or avail Services during such pre-scheduled maintenance, we cannot guarantee the
				availability of the Services and/or functionality of the Platform.
			</li>
			<li>
				Termination/ Suspension of Accounts:
				We may terminate your usage of the Platform at any time for any reason, including breach of the Terms
				and
				Conditions. We have the right (but not the obligation) to refuse to grant access to Platform. Except for
				the
				rights and license granted in these terms, we reserve all other rights and grant no other rights or
				licenses,
				implied or otherwise.
				Once temporarily suspended, indefinitely suspended or terminated, the User may not continue to use the
				Platform
				under the same account, a different account or re-register under a new account. On termination of an
				account
				due
				to the reasons mentioned herein, such User shall no longer have access to data, messages and other
				material
				kept
				on the Platform by such User. All provisions of the TOS, which by their nature should survive
				termination,
				shall
				survive termination, including, without limitation, warranty disclaimers, indemnity and limitations of
				liability.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold">19. Disclaimer</span>
		<br />
		THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY CONTENT) IS PROVIDED “AS IS” AND “AS AVAILABLE” AND IS WITHOUT
		WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE,
		NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE
		OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. THE COMPANY and SERVICE PROVIDER
		(INCLUDING) ITS DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, SPONSORS AND PARTNERS DO NOT WARRANT THAT: (A) THE
		SERVICE WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY DEFECTS OR ERRORS WILL BE
		CORRECTED; (C) ANY CONTENT OR SOFTWARE AVAILABLE AT OR THROUGH THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL
		COMPONENTS; (D) ANY INFORMATION AVAILABLE ON THE PLATFORM IS ACCURATE; OR (E) THE RESULTS OF USING THE SERVICE
		WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE SERVICE IS SOLELY AT YOUR OWN RISK.

		WE DON’T PROMISE TO STORE OR KEEP SHOWING ANY INFORMATION AND CONTENT THAT YOU’VE POSTED. WEQUITY IS NOT A
		STORAGE SERVICE. YOU AGREE THAT WE HAVE NO OBLIGATION TO STORE, MAINTAIN OR PROVIDE YOU A COPY OF ANY CONTENT OR
		INFORMATION THAT YOU OR OTHERS PROVIDE, EXCEPT TO THE EXTENT REQUIRED BY APPLICABLE LAW AND AS NOTED IN OUR
		PRIVACY POLICY.

		YOU (BOTH INDIVIDUAL AND ENTERPRISE) HEREBY ACKNOWLEDGE AND AGREE THAT YOU WILL SHALL ONLY PROVIDE TRUE AND
		CORRECT INFORMATION AND IN THE CASE OF CREATING AN ACCOUNT YOU UNDERTAKE TO AT ALL TIMES KEEP THE INFORMATION UP
		TO DATE. UNDER NO CIRCUMSTANCES THE COMPANY WILL BE LIABLE ON ACCOUNT OF ANY INACCURACY OF INFORMATION PROVIDED
		BY YOU ON THIS PORTAL. WE COLLECT AND PUBLISH INFORMATION FROM THE PUBLIC DOMAIN (INCLUDING FROM INFORMATION
		AVAILABLE ON SOCIAL MEDIA OR OTHER THIRD PARTY INFORMATION PROVIDERS). WE DO NOT MAKE ANY WARRANTY REGARDING THE
		ACCURACY OF SUCH INFORMATION. IT IS THE RESPONSIBILITY OF THE USER TO FURTHER RESEARCH THE INFORMATION ON THE
		SITE.
		<br />
		<br />
		As we share information collected from the public domain, it is possible that there may be inaccuracies and
		errors, such as attributing credit incorrectly to a User or not attributing credit correctly to the actual
		deserving party. Any discrepancy found in the information present on the platform can be brought to our notice
		by emailing us at Cs@talentgridnow.com or by using the in-app feature to report it, with adequate proof.
		Such complaints will be verified and addressed on priority within 3 business days of receipt. If your complaint
		has not been addressed within such period, you may please contact our grievance officer.
	</div>
	<div>
		<span style="font-weight: bold"><br />20. Indemnification</span>
		<br />
		You agree to defend, indemnify, and hold harmless the Company, its affiliates, subsidiaries, joint
venture partners, and each of their respective employees, contractors, directors, suppliers, and
representatives (collectively referred to as &quot;Indemnified Parties&quot;) from and against any and all
liabilities, losses, claims, damages, expenses, and costs (including reasonable attorneys’ fees,
and court costs) that arise from or relate to: (i) Any failure by you, to render the services or your
unavailability to fulfil your obligations, which results in damages or losses to the Company or third
parties seeking your services; or (ii) Your use or, misuse of, or access to, the Services and
Platform; or (iii) Your violation of the Terms and Conditions, any applicable law, contract, policy,
regulation, or other obligation. ; or (iv) Any claims brought against the Company or any
Indemnified Party by a third party arising out of your actions, inactions, or any other conduct
related to the use of the Platform or the services provided.
We reserve the right to assume the exclusive defense and control of any matter otherwise
subject to indemnification by you, in which event you shall cooperate fully with us in the defense
of such matter. You agree not to settle any claim without the prior written consent of the
Company.
	</div>
	<div>
		<span style="font-weight: bold"><br />21. Limitation of Liability</span>
		<br />
		TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL COMPANY (INCLUDING ITS DIRECTORS, EMPLOYEES, AGENTS,
		SPONSORS, PARTNERS, SUPPLIERS, CONTENT PROVIDERS, LICENSORS OR RESELLERS,) BE LIABLE UNDER CONTRACT, TORT,
		STRICT LIABILITY, NEGLIGENCE OR ANY OTHER LEGAL OR EQUITABLE THEORY WITH RESPECT TO THE SERVICES (I) FOR ANY
		LOST PROFITS, DATA LOSS, LOSS OF GOODWILL OR OPPORTUNITY, OR SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR
		CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER, (II) FOR YOUR RELIANCE ON THE SERVICES (III) FOR ANY DAMAGES (IV)
		FOR ANY MATTER BEYOND ITS OR THEIR REASONABLE CONTROL, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF
		ANY OF THE AFOREMENTIONED DAMAGES.
	</div>
	<div>
		<span style="font-weight: bold"><br />22. Exemptions to liability of Company</span>
		<br />
		You further agree and confirm that Company shall not be responsible, in any manner whatsoever, for any
		delay/unavailability of Services or failure to meet its obligations under the Terms and Conditions, which may be
		caused, directly or indirectly, due to:
		<ol type="I">
			<li>
				your failure to cooperate;
			</li>
			<li>
				your unavailability and/or unresponsiveness;
			</li>
			<li>
				your failure to provide accurate and complete information;
			</li>
			<li>
				your failure to provide or facilitate the submission of User Materials in timely manner;
			</li>
			<li>
				any event beyond Company’s reasonable control or
			</li>
			<li>
				Inconsistency of data displayed on the platform
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />23. Governing Law</span>
		<br />
		This Agreement shall be governed by and construed in accordance with the laws of India without regard to the
		conflict of law provisions thereof. All claims, differences and disputes arising under or in connection with or
		in relation hereto the Platform or Services, the Terms or any transactions entered into on or through the
		Platform or Services shall be subject to the exclusive jurisdiction of the courts at Karnataka, India and you
		hereby accede to and accept the jurisdiction of such courts.
	</div>
	<div>
		<span style="font-weight: bold"><br />24. Miscellaneous</span>
		<ol type="I">
			<li>
				The Terms and Conditions are the entire agreement and understanding between you and Company with respect
				to
				the Services and usage of Platform.
			</li>
			<li>
				If any provision of the Terms and Conditions are found to be unenforceable or invalid, that
				provision
				will
				be limited or eliminated to the minimum extent necessary so that the Terms and Conditions will otherwise
				remain
				in full force and effect and enforceable.
			</li>
			<li>
				The failure of either party to exercise in any respect any right provided for herein shall not be
				deemed a
				waiver of any further rights hereunder.
			</li>
			<li>
				The Terms and Conditions are personal to you, and are not assignable or transferable by you except
				with
				Company’s prior written consent. Company may assign, transfer or delegate any of its rights and
				obligations
				hereunder without any consent.
			</li>
			<li>
				No agency, partnership, joint venture, or employment relationship is created as a result of the Terms
				and
				Conditions and neither party has any authority of any kind to bind the other in any respect.
			</li>
			<li>
				VI. All notices under the Terms and Conditions will be in writing and will be deemed to have been duly
				given
				when received, if personally delivered or sent by certified or registered mail, return receipt requested
				at
				the
				registered address mentioned in this Terms of Use; when receipt is electronically confirmed, if
				transmitted
				by
				facsimile or e-mail at [Cs@talentgridnow.com]; or two days after it is sent, if sent for next day
				delivery by
				recognized overnight delivery service.
			</li>
		</ol>
	</div>
	<div>
		<span style="font-weight: bold"><br />25. Grievance Redressal Mechanism</span>
		<br />
		In furtherance of the Information Technology Act, 2000 (“IT Act”) and the Information Technology (Intermediary
		Guidelines and Digital Media Ethics Code) Rules, 2021 (“Intermediary Guidelines”) a grievance officer is
		appointed to ensure compliance with the IT Act and the Intermediary guidelines.
		In case you find any inaccurate information on the Platform (such as attributing credit incorrectly to a User or
		not attributing credit correctly to the actual deserving party), please notify us with adequate proof by
		emailing us at Cs@talentgridnow.com, or use the in-app feature to report it. We shall verify and address
		such reports on priority within 3 business days of receipt. If the complaint has not been addressed within such
		period, you may please report the same to our grievance officer as specified below.

		Any other grievances with regard to content and or comment or breach of the Terms of Use shall be taken up with
		the designated grievance officer as mentioned below in writing or through email signed with the electronic
		signature to:

		<span style="font-weight: bold"><br />Name: Grievance officer</span>
		<span style="font-weight: bold"><br />Contact Details: Support@talentgridnow.com</span>
		<span style="font-weight: bold"><br />Designation of such officer: Senior Grievance officer</span>

		The grievance officer shall revert to every complaint within 24 hours of receipt of the complaint. Further, the
		Company shall take best possible efforts to redress the complaint within 15 days of receipt of the complaint.
		Any suggestions by Company regarding use of the Services shall not be construed as a warranty.
	</div>
	<div>
		<span style="font-weight: bold"><br />26. Contact</span>
		<br />
		If you have any questions regarding the Services or usage of the Platform, please contact Company at
		Cs@talentgridnow.com. Please note that for the purpose of validation, you shall be required to provide
		information (including, but not limited to contact number or registered mobile number, etc.) for the purpose of
		validation and taking your service request.
	</div>
	<div>
		<span style="font-weight: bold"><br />27. Payment Policy</span>
		<br />
		Our mobile application acts as a platform for users to hire talent, hire studios or locations for
project-based work. The price per assignment is agreed upfront between the hirer and talent.
Upon successful completion of a project, the talent will raise an invoice through the platform,
which the user (client) is required to pay in a timely manner. All payments are processed through
our secure, integrated payment gateway. Users are responsible for ensuring that payment is
made as per the agreed terms with the talent. Any delays or failures to pay may result in further
action as outlined in the platform’s terms of service.
	</div>
	<div>
		<span style="font-weight: bold"><br />28. Refund policy</span>
		<br />
		In cases where an advance is paid and where a project is canceled before completion, a refund
may be applicable depending on the amount of work completed and resources expended by the
talent. If a project is canceled, both the user and the talent agree that the talent should be fairly
compensated for any time, effort, or expenses incurred up to the point of cancellation. If no significant progress has been made, the user may request a partial or full refund, subject to
review by our support team. Refunds will be processed to the original payment method within 7-
10 business days of confirmation. To request a refund due to project cancellation or non-delivery
of services, users must contact our support team within 10 business days by
emailing [ Cs@talentgridnow.com ]. All refund requests are assessed on a case-by-case basis.
	</div>
</div>
	`;

	return (
		<SafeAreaView style={{ flex: 1, backgroundColor: theme.colors.black }}>
			<Header name="Terms and conditions" />
			<ScrollView>
				<RenderHtml
					systemFonts={[...defaultSystemFonts, theme.fontFamily.cgRegular, theme.fontFamily.cgBold]}
					contentWidth={CONSTANTS.screenWidth}
					source={{ html: source }}
					tagsStyles={{
						div: {
							color: 'whitesmoke',
							fontSize: theme.fontSize.typographyMd,
							paddingHorizontal: theme.padding.xs,
							fontFamily: theme.fontFamily.cgRegular,
						},
						p: {
							marginBottom: 12,
							fontFamily: theme.fontFamily.cgRegular,
						},
						strong: {
							fontFamily: theme.fontFamily.cgBold,
						},
					}}
				/>
			</ScrollView>
		</SafeAreaView>
	);
}

const stylesheet = StyleSheet.create({
	padding: {
		paddingTop: Platform.OS === 'ios' ? 50 : 0,
		backgroundColor: 'black',
	},
	container: {
		flex: 1,
		backgroundColor: 'black',
	},
});
